# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

caldleVersion=2.4.0
loomVersion=1.15-SNAPSHOT

caldle.useDevAuth=true
caldle.devAuth.module=fabric
caldle.devAuth.version=1.2.2
caldle.devAuth.configuration=modLocalRuntime

modVersion=1.0.0
mavenGroup=fr.lacaleche.mui
archiveBaseName=modernui-mc-lite
