[versions]
minecraft = "1.21.8"
fabric-loader = "0.18.4"
fabric = "0.136.1+1.21.8"

modernui = "3.13.0"
arc3d = "2026.2.0"

junit = "5.10.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
modernui-core = { module = "dev.icyllis:modernui-core", version.ref = "modernui" }
arc3d-core = { module = "dev.icyllis:arc3d-core", version.ref = "arc3d" }
arc3d-sketch = { module = "dev.icyllis:arc3d-sketch", version.ref = "arc3d" }
arc3d-engine = { module = "dev.icyllis:arc3d-engine", version.ref = "arc3d" }
arc3d-granite = { module = "dev.icyllis:arc3d-granite", version.ref = "arc3d" }
arc3d-opengl = { module = "dev.icyllis:arc3d-opengl", version.ref = "arc3d" }
arc3d-vulkan = { module = "dev.icyllis:arc3d-vulkan", version.ref = "arc3d" }
arc3d-compiler = { module = "dev.icyllis:arc3d-compiler", version.ref = "arc3d" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
